language: node_js
node_js:
  - 6
  - 4
install:
  - npm install -g codecov
  - npm install mocha
  - npm install -g istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov